version: "2"
plugins:
  sonar-python:
    enabled: true
  pylint:
    enabled: true
  bandit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - python
  fixme:
    enabled: true
  markdownlint:
    enabled: true
  pep8:
    enabled: true
  radon:
    enabled: true
ratings:
  paths:
    - "**.inc"
    - "**.module"
    - "**.py"
exclude_patterns:
  - dist/
  - tests/
  - build/
