---
include:
  - project: nci-gdc/gitlab-templates
    ref: 0.3.1
    file:
      - templates/global/full.yaml
      - templates/python/full.yaml
      - templates/common/python.yaml
      - templates/common/docker.yaml
      - templates/deployments/salt-service.yaml

.services:
  allow_failure: true
  stage: deploy
  when: manual
  parallel:
    matrix:
      - DEPLOY_SERVICE_LIST: [ indexd ]

pre-commit:
  variables:
    PRE_COMMIT_VERSION: 3.4.0

tox:
  parallel:
    matrix:
      - BUILD_PY_VERSION: [python3.7, python3.8, python3.9, python3.10, python3.11]
  services:
    - name: docker.osdc.io/ncigdc/ci-postgres-13:${BASE_CONTAINER_VERSION}
      alias: postgres
  variables:
    PG_INDEXD_USER: test
    PG_INDEXD_PASS: test
    PG_INDEXD_HOST: postgres
    PG_INDEXD_DROP_DB: 'false'
    PG_INDEXD_ROOT_USER: test
    PG_INDEXD_ROOT_PASS: test
    POSTGRES_DB: indexd_test
    POSTGRES_USER: test
    POSTGRES_PASSWORD: test
    POSTGRES_HOST_AUTH_METHOD: trust
  script:
    - mkdir -p /usr/share/man/man1
    - apt update && apt -y install openjdk-8-jdk-headless
    - java -version
    - pip install 'tox < 4'
    - tox -e py

release:
  variables:
    RELEASE_PY_VERSION: python3.7
  before_script:
    - git fetch --unshallow || true
  after_script:
    - python setup.py --version > VERSION.txt
  artifacts:
    paths:
      - VERSION.txt
    expire_in: 1 week
