---
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Python.gitlab-ci.yml
include:
  - project: nci-gdc/gitlab-templates
    ref: master
    file:
      - templates/docker/ssh/.gitlab-ci.template.yml
      - templates/builds/python/cache/.gitlab-ci.template.yml
      - templates/deployments/environments/.gitlab-ci-template.yml

# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: docker.osdc.io/ncigdc/python38-builder-jdk11:1.4.0

before_script:
  - python --version  # For debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

tox-py38:
  tags:
    - dind
  image: docker.osdc.io/ncigdc/python38-builder-jdk11:1.4.0
  services:
    - name: docker.osdc.io/postgres:13
      alias: postgres
    - name: docker.osdc.io/ncigdc/elasticsearch-docker:7.7.1
      alias: elasticsearch
  script:
    - !reference [.load_github_key, script]
    - pip install tox
    - tox
  variables:
    POSTGRES_HOST_AUTH_METHOD: trust
    ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    xpack_security_enabled: "false"
    discovery_type: "single-node"

tox-py27:
  tags:
    - dind
  image: docker.osdc.io/ncigdc/python27-builder:1.4.0
  services:
    - name: docker.osdc.io/postgres:13
      alias: postgres
    - name: docker.osdc.io/ncigdc/elasticsearch-docker:7.7.1
      alias: elasticsearch
  script:
    - !reference [.load_github_key, script]
    - apt update && apt install openjdk-11-jdk -y
    - pip install tox
    - tox
  variables:
    POSTGRES_HOST_AUTH_METHOD: trust
    ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    xpack_security_enabled: "false"
    discovery_type: "single-node"

run:
  script:
    - !reference [.load_github_key, script]
    - python setup.py bdist_wheel
    # an alternative approach is to install and run:
    - pip install dist/*
    # run the command here
  artifacts:
    paths:
      - dist/*.whl
