---
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Python.gitlab-ci.yml
include:
  - project: nci-gdc/gitlab-templates
    ref: master
    file:
      - templates/global/full.yaml
      - templates/python/full.yaml

tox-py38:
  stage: test
  tags:
    - dind
  image: docker.osdc.io/ncigdc/python38-builder-jdk11:1.4.0
  services:
    - name: docker.osdc.io/ncigdc/ci-postgres-13:chore_add-python3.9_and_3.10-19
      alias: postgres
    - name: docker.osdc.io/ncigdc/ci-elasticsearch-7:chore_add-python3.9_and_3.10-19
      alias: elasticsearch
  script:
    - !reference [.load_github_key, script]
    - !reference [.python_venv, script]
    - pip install tox
    - tox
  variables:
    POSTGRES_HOST_AUTH_METHOD: trust
  artifacts:
    when: always
    reports:
      cobertura: coverage.xml
      junit: test-reports/results.xml

tox-py27:
  stage: test
  tags:
    - dind
  image: docker.osdc.io/ncigdc/python27-builder:1.4.0
  services:
    - name: docker.osdc.io/ncigdc/ci-postgres-13:chore_add-python3.9_and_3.10-19
      alias: postgres
    - name: docker.osdc.io/ncigdc/ci-elasticsearch-7:chore_add-python3.9_and_3.10-19
      alias: elasticsearch
  script:
    - !reference [.load_github_key, script]
    - mkdir -p /usr/share/man/man1
    - apt update && apt install openjdk-11-jdk -y --no-install-recommends
    - !reference [.python_venv, script]
    - pip install tox
    - tox
  variables:
    POSTGRES_HOST_AUTH_METHOD: trust
  artifacts:
    when: always
    reports:
      cobertura: coverage.xml
      junit: test-reports/results.xml
