---
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Python.gitlab-ci.yml
include:
  - project: nci-gdc/gitlab-templates
    ref: master
    file:
      - templates/global/full.yaml
      - templates/python/full.yaml

.tox_services:
  services:
    - name: docker.osdc.io/ncigdc/ci-postgres-13:master-32
      alias: postgres
    - name: docker.osdc.io/ncigdc/ci-elasticsearch-7:master-32
      alias: elasticsearch

tox:
  before_script:
    - mkdir -p /usr/share/man/man1
    - apt update && apt install openjdk-11-jdk -y --no-install-recommends

.python_versions:
  parallel:
    matrix:
      - REPO_PY_VERSION: [python27, python38]
