---
include:
  - project: nci-gdc/gitlab-templates
    ref: 0.3.1
    file:
      - templates/global/full.yaml
      - templates/python/full.yaml
      - templates/common/python.yaml
      - templates/deployments/salt-service.yaml

.services:
  allow_failure: true
  stage: deploy
  when: manual
  parallel:
    matrix:
      - DEPLOY_SERVICE_LIST: [ indexd ]

tox:
  parallel:
    matrix:
      - BUILD_PY_VERSION: [python3.7, python3.8, python3.9, python3.10, python3.11]
  services:
    - name: docker.osdc.io/ncigdc/ci-postgres-13:${BASE_CONTAINER_VERSION}
      alias: postgres
  variables:
    PG_INDEXD_USER: test
    PG_INDEXD_PASS: test
    PG_INDEXD_HOST: postgres
    PG_INDEXD_DROP_DB: 'false'
    PG_INDEXD_ROOT_USER: test
    PG_INDEXD_ROOT_PASS: test
    POSTGRES_DB: indexd_test
    POSTGRES_USER: test
    POSTGRES_PASSWORD: test
    POSTGRES_HOST_AUTH_METHOD: trust
  script:
    - mkdir -p /usr/share/man/man1
    - apt update && apt -y install openjdk-8-jdk-headless
    - java -version
    - pip install 'tox < 4'
    - tox -e py

release:
  variables:
    RELEASE_PY_VERSION: python3.7
  before_script:
    - git fetch --unshallow || true
  after_script:
    - python setup.py --version > VERSION.txt
  artifacts:
    paths:
      - VERSION.txt
    expire_in: 1 week

Docker build:
  stage: release
  before_script:
    - apk add bash git
  services:
    - docker:$DOCKER_VERSION-dind
  script:
    - ls
    - !reference [.load_github_key, script]
    - /bin/bash docker.sh
  except:
    - tags
  tags:
    - dind
  dependencies:
    - release

Docker build git tag:
  stage: release
  before_script:
    - apk add bash git
    - git fetch --unshallow || true
  services:
    - docker:$DOCKER_VERSION-dind
  script:
    - BRANCH_NAME=$(git branch -a --contains tags/${CI_COMMIT_TAG} | grep origin | sed 's/.*origin\///' | tail -1)
    - CLEAN_BRANCH_NAME=${BRANCH_NAME/\//-}
    - docker pull docker.osdc.io/ncigdc/$CI_PROJECT_NAME:${CLEAN_BRANCH_NAME}
    - docker tag docker.osdc.io/ncigdc/$CI_PROJECT_NAME:${CLEAN_BRANCH_NAME} $DOCKER_RELEASE_REGISTRY/ncigdc/$CI_PROJECT_NAME:${CI_COMMIT_TAG}
    - docker push $DOCKER_RELEASE_REGISTRY/ncigdc/$CI_PROJECT_NAME:${CI_COMMIT_TAG}
  only:
    - tags
  tags:
    - dind
