---
include:
  - project: nci-gdc/gitlab-templates
    ref: master
    file:
      - templates/artifacts/python-docker-service.yaml

variables:
  SERVICE_NAME: indexd

tox:
  parallel:
    matrix:
      - BUILD_PY_VERSION: [python3.8, python3.9, python3.10]
  services:
    - name: docker.osdc.io/ncigdc/ci-postgres-13:${BASE_CONTAINER_VERSION}
      alias: postgres
  variables:
    PG_INDEXD_USER: test
    PG_INDEXD_PASS: test
    PG_INDEXD_HOST: postgres
    PG_INDEXD_DROP_DB: 'false'
    PG_INDEXD_ROOT_USER: test
    PG_INDEXD_ROOT_PASS: test
    POSTGRES_DB: indexd_test
    POSTGRES_USER: test
    POSTGRES_PASSWORD: test
    POSTGRES_HOST_AUTH_METHOD: trust
    BASE_CONTAINER_VERSION: 3.0.6
  script:
    - mkdir -p /usr/share/man/man1
    - dnf -y install java-11-amazon-corretto-headless
    - dnf upgrade wget
    - java -version
    - pip install 'tox > 4'
    - tox -e py

.deploy-service-with-salt:
  before_script:
    - export DEPLOY_SERVICE_TAG=${CI_COMMIT_TAG:-$CI_COMMIT_SHA}

.services:
  allow_failure: true
  stage: deploy
  when: manual
  parallel:
    matrix:
      - DEPLOY_SERVICE_LIST: [ indexd ]
