repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-yaml
        exclude: ^helm/templates/
      - id: check-toml
      - id: check-json
      - id: pretty-format-json
        args: [--autofix]
        exclude: ^gdcapi/data/bam/gencode_.._gene_mapping.json
      - id: end-of-file-fixer
      - id: no-commit-to-branch
        args: [--branch, develop, --branch, master, --pattern, release/.*]
  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black
        additional_dependencies: [click==8.0.4]
  - repo: git@github.com:Yelp/detect-secrets
    rev: v0.13.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
