---
version: '3.3'
services:

  postgres:
    image: postgres:9.4
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  app:
    image: docker.osdc.io/ncigdc/jenkins-agent:1.0.1
    environment:
      SWAGGER_URL: https://nexus.osdc.io/repository/maven-public/io/swagger/codegen/v3/swagger-codegen-cli/3.0.25/swagger-codegen-cli-3.0.25.jar
      SSH_AUTH_SOCK: $SSH_AUTH_SOCK
      HTTPS_PROXY: http://cloud-proxy:3128
      HTTP_PROXY: http://cloud-proxy:3128
      NO_PROXY: localhost
    volumes:
      - .:/home/jenkins
      - $SSH_AUTH_SOCK:$SSH_AUTH_SOCK
    command: bash -c "wait-for-it localhost:5432 -t 120 && tox --recreate"
    network_mode: service:postgres
    depends_on: # other containers it needs in order to run
      - postgres
