apiVersion: v1
kind: ConfigMap
metadata:
    name: indexd-conf
    labels:
        {{- include "indexd.labels" . | nindent 6 }}
data:
{{ (tpl (.Files.Glob "files/indexd.conf").AsConfig .) | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: indexd-local-settings
    labels:
        {{- include "indexd.labels" . | nindent 6 }}
data:
{{ (.Files.Glob "files/local_settings.py").AsConfig | indent 4 }}
